### ISSUE TITLE
Strange running error

### ISSUE THREAD

**Issue by SammyAgrawal** [leap-stc/eNATL_feedstock#4]
Not sure if I'm doing anything differently than before, but I can't debug this error: 

`pangeo-forge-runner bake \ --repo=./ \ --Bake.recipe_id=eNATL60_BLBT02 \ -f configs/config_local.py`

FileNotFoundError: [Errno 2] No such file or directory: 'hg'

Happened on hub as well, tried after kept failing on local. 

Apparently hg is something called "mercurial"

**Comment by SammyAgrawal** [comment]
Okay did not know needed to use object, not id

  - id: eNATL60_BLBT02
    object: "eNATL60:eNATL60_BLBT02"

**Comment by jbusecke** [comment]
Can we close this?
